#!/usr/bin/python3

class Libro: 
    def __init__(self, id_libro, autor, nombre_libro):
        self.id_libro = id_libro
        self.autor = autor 
        self.nombre_libro = nombre_libro
        self.esta_prestado = False

    def __str__(self):
        return f"Libro({self.id_libro}, {self.autor}, {self.nombre_libro})"
    
    def __repr__(self):
        return self .__str__()

class Biblioteca:

    def __init__(self):
        self.libros = {}


    def agregar_libro(self, libro):
        if libro.id_libro not in self.libros:
            self.libros[libro.id_libro] = libro
        else:
            print(f"\n[!] No es posible agregar el libro con ID {libro.id_libro}")

    def prestar_libro(self, id_libro):
        if id_libro in self.libros and not self.libros[id_libro].esta_prestado: 
            self.libros[id_libro].esta_prestado = True
        else:
            print(f"No es posible prestar el libro con ID: {id_libro}")
    @property
    def mostrar_libros(self):
        return [libro for libro in self.libros.values() if not libro.esta_prestado]
    
    @property
    def mostrar_libros_prestados(self):
        return [libro for libro in self.libros.values() if libro.esta_prestado]

class BibliotecaInfantil(Biblioteca):

    def __init__(self):
        super().__init__()
        self.libros_ninos = {}
    
    def agregar_libro(self, libro, es):
        super().agregar_libro(libro)
        self.libros_ninos[libro.id_libro] = es

    def prestar_libro(self, id_libro, es):
        if id_libro in self.libros and self.libros_ninos[id_libro] == es and not self.libros[id_libro].esta_prestado: 
            self.libros[id_libro].esta_prestado = True
        else:
            print(f"No es posible prestar el libro con ID: {id_libro}")
        

    @property
    def mostrar_estado_libros_para_ninos(self):
        return self.libros_ninos
    
if __name__ == '__main__':
    
    biblioteca = BibliotecaInfantil()
    
    libro1 = Libro(1, "Marcelo Vazquez", "¿Como ser un Lammer de Potencia maxima?")
    libro2 = Libro(2, "Pepito Manolete", "Aprende a colorear desde cero")

    biblioteca.agregar_libro(libro1, es=False)
    biblioteca.agregar_libro(libro2, es=True)

    print(f"[+] Libros en la bibliteca: {biblioteca.mostrar_libros}")

    biblioteca.prestar_libro(1, es=False)

    print(f"[+] Libros en la bibliteca: {biblioteca.mostrar_libros}")
    print(f"[+] Libros prestados: {biblioteca.mostrar_libros_prestados}")
    print(f"[+] Libros para niños: {biblioteca.mostrar_estado_libros_para_ninos}")


